### ISSUE TITLE
Tidy up some magic numbers

### ISSUE THREAD

**Issue by alexrussell** [Cotidia/react-ui#1]
For example, Help allows the parent component to set its position, but randomly adds 6 pixels:

``` js
if (this.props.position) {
    helpStyle = {
        bottom: this.props.position + 6
   }
}
```

**Comment by guillaumepiot** [comment]
Due to the position of the help component, it is influence by the height of the form__control container and the padding/margin around it. Ideally, it should be positioned purely with CSS. An alternative should be implemented perhaps using the examples as benchmark.
